### ISSUE TITLE
Type must be provided to call2

### ISSUE THREAD

**Issue by femto** [ruby-llvm/ruby-llvm#210]
when running samples/fp.rb (ruby-llvm version 17.0.0)

```
/Users/femtozheng/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-llvm-17.0.0/lib/llvm/core/builder.rb:948:in `call2_infer_function_and_type': Type must be provided to call2 when function argument is not a function type: ptr %0 (ArgumentError)

      raise ArgumentError, "#{msg} #{fun}" if !fun2.is_a?(Function) && type.nil?
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /Users/femtozheng/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-llvm-17.0.0/lib/llvm/core/builder.rb:957:in `call2'
        from /Users/femtozheng/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-llvm-17.0.0/lib/llvm/core/builder.rb:938:in `call'
        from samples/fp.rb:29:in `block (2 levels) in <main>'
        from /Users/femtozheng/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-llvm-17.0.0/lib/llvm/core/value.rb:164:in `build'
        from samples/fp.rb:28:in `block in <main>'
        from /Users/femtozheng/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-llvm-17.0.0/lib/llvm/core/module.rb:180:in `add'
        from samples/fp.rb:27:in `<main>'

	
```

**Comment by thoughtafter** [comment]
Yeah, looks like that didn't survive the switch to opaque pointers.
