### ISSUE TITLE
Function 'LLVMAddFunctionAttr' not found in [libLLVM-5.0.so.1] (FFI::NotFoundError)

### ISSUE THREAD

**Issue by eterps** [ruby-llvm/ruby-llvm#61]
After a clean install of the latest ref on Ubuntu 18:04 you get Function 'LLVMAddFunctionAttr' not found when you run the provided sample code. I created [a Dockerfile](https://gist.github.com/eterps/59a40746ad09263427274cefaa1409e0) for easier testing and clean reproducability.

Steps to reproduce the above mentioned error:

```shell
wget https://gist.githubusercontent.com/eterps/59a40746ad09263427274cefaa1409e0/raw/149a21c30873b6e6411ec0c1443730bec96150b3/Dockerfile
docker build -t rbllvmtest . && docker run -it rbllvmtest
```

(also tested with llvm-4.0, but same error: 'Function 'LLVMAddFunctionAttr' not found in [libLLVM-4.0.so.1] (FFI::NotFoundError)')

**Comment by eterps** [comment]
To be clear, the current release version of this gem works on Ubuntu 16.04:

```shell
wget https://gist.githubusercontent.com/eterps/f67e2da88565270db6f8745c26043b29/raw/8db89903de51098334d297b6c3334f5ecff92198/Dockerfile
docker build -t rbllvmtest1604 . && docker run -it rbllvmtest1604
...
Successfully built c68548d08c10
Successfully tagged rbllvmtest1604:latest
; ModuleID = 'hello'

@hello = private unnamed_addr constant [14 x i8] c"Hello, World!\00"

; Function Attrs: nounwind
declare i32 @puts(i8* nocapture) #0

define i32 @main() {
  %1 = call i32 @puts(i8* getelementptr inbounds ([14 x i8]* @hello, i32 0, i32 0))
  ret i32 0
}

attributes #0 = { nounwind }
------------------------------
Hello, World!
```

But llvm-3.5 is not available anymore on Ubuntu 18.04.

I think the focus should be on getting the earliest version working on recent Linux/Mac machines.

**Comment by thoughtafter** [comment]
Good catch. LLVMAddFunctionAttr was removed in LLVM 4. The big issue is that ffi_gen has been broken since before LLVM 4 so core_ffi.rb is out of date. I mentioned that in #59 but it may deserve a separate issue. I believe fixing ffi_gen will be highly useful to keeping this project well maintained.

However, to fix this issue I believe we can sidestep that work for now and try and preserve the existing API which is Function.add_attribute. Instead of mapping to LLVMAddFunctionAttr it needs to use the new LLVM 4+ attribute API. Let me see what I can do.

**Comment by thoughtafter** [comment]
Try out the latest master. There are some issues that I will add related to this but this should get you past this.

**Comment by eterps** [comment]
On a clean Ubuntu 16.04 & 18.04 I get past the Function 'LLVMAddFunctionAttr' not found error, but get a Segmentation fault instead:

```
/var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/lib/llvm/core/value.rb:72: [BUG] Segmentation fault at 0x0000560301a4da58
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0041 e:000040 CFUNC  :add_attribute_at_index
c:0005 p:0055 s:0034 e:000033 METHOD /var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/lib/llvm/core/value.rb:72
c:0004 p:0016 s:0025 e:000024 BLOCK  /var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/samples/hello.rb:22
c:0003 p:0105 s:0020 e:000019 METHOD /var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/lib/llvm/core/module.rb:168
c:0002 p:0109 s:0011 E:000178 EVAL   /var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/samples/hello.rb:20 [FINISH]
c:0001 p:0000 s:0003 E:001e50 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/samples/hello.rb:20:in `<main>'
/var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/lib/llvm/core/module.rb:168:in `add'
/var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/samples/hello.rb:22:in `block in <main>'
/var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/lib/llvm/core/value.rb:72:in `add_attribute'
/var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/lib/llvm/core/value.rb:72:in `add_attribute_at_index'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f1c6a4e9cf4 RBP: 0x0000000000000001 RSP: 0x00007fff9104ed28
 RAX: 0x00007f19b7bda010 RBX: 0x00007fff9104ee20 RCX: 0x00007f1c63de6390
 RDX: 0x00000002ac20c380 RDI: 0x00007f19b7bda010 RSI: 0x00005600558416f8
  R8: 0x00000000ffffffff  R9: 0x0000000000000000 R10: 0x0000000000000022
 R11: 0x0000000000000246 R12: 0x000056005585c850 R13: 0x0000560301a4da78
 R14: 0x00007fff9104eda0 R15: 0x00000002ac20c380 EFL: 0x0000000000010216

-- C level backtrace information -------------------------------------------
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a909685) [0x7f1c6a909685]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a9098bc) [0x7f1c6a9098bc]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a7d3884) [0x7f1c6a7d3884]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a8996c2) [0x7f1c6a8996c2]
/lib/x86_64-linux-gnu/libc.so.6(0x7f1c6a399f20) [0x7f1c6a399f20]
/lib/x86_64-linux-gnu/libc.so.6(0x7f1c6a4e9cf4) [0x7f1c6a4e9cf4]
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZNK4llvm13AttributeList13addAttributesERNS_11LLVMContextEjRKNS_11AttrBuilderE+0x9e) [0x7f1c651cecde]
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZNK4llvm13AttributeList12addAttributeERNS_11LLVMContextEjNS_9AttributeE+0x9f) [0x7f1c651cf13f]
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZN4llvm8Function12addAttributeEjNS_9AttributeE+0x3d) [0x7f1c6524a79d]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f1c68020dae]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f1c6802071f]
/var/lib/gems/2.5.0/gems/ffi-1.9.25/lib/ffi_c.so(rbffi_CallFunction+0xe7) [0x7f1c68230817]
/var/lib/gems/2.5.0/gems/ffi-1.9.25/lib/ffi_c.so(0x11054) [0x7f1c68234054]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a8f1fa9) [0x7f1c6a8f1fa9]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a8f7370) [0x7f1c6a8f7370]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a8fc744) [0x7f1c6a8fc744]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1c6a7d70c4) [0x7f1c6a7d70c4]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(ruby_exec_node+0x1d) [0x7f1c6a7d8f4d]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(ruby_run_node+0x1e) [0x7f1c6a7db42e]
ruby(0x560053c7e8cb) [0x560053c7e8cb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f1c6a37cb97]
ruby(_start+0x2a) [0x560053c7e8fa]

-- Other runtime information -----------------------------------------------

* Loaded script: /var/lib/gems/2.5.0/bundler/gems/ruby-llvm-b17d28e6768b/samples/hello.rb
```

**Comment by eterps** [comment]
Yes, it works, thank you! I will continue testing for Homebrew on Linux and Mac.

**Comment by eterps** [comment]
It works with Linuxbrew on Ubuntu 18:04, and also with Homebrew on Mac.
On Mac I had to do:

```
brew install llvm@5 --shared
export PATH="/usr/local/opt/llvm@5/bin:$PATH"
bundle install
ln -s /usr/local/opt/llvm@5/lib/libLLVM.dylib /usr/local/lib/libLLVM-5.0.dylib
bundle exec ruby hello.rb
```

The process could probably be a bit more streamlined in the future, but for now this works fine, I am closing this one.
